FROM node:20-alpine AS builder
WORKDIR /usr/src/web

COPY web/package.json web/package-lock.json* ./
COPY web/tsconfig.json web/next.config.js ./
RUN npm ci

COPY web ./
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /usr/src/web
COPY --from=builder /usr/src/web/.next .next
COPY --from=builder /usr/src/web/public ./public
COPY --from=builder /usr/src/web/package.json ./package.json
RUN npm ci --production

EXPOSE 3000
CMD ["npm", "run", "start"]
